**Python for Data Science**

# Ipython : au delà du python classique

## Introduction

# Introduction à Numpy

Numpy?

---
Numpy est une librarie python destinée au calcul scientifique, sur le modèle matlab.

---


## Les types de données

Un langage fortement et dynamiquement typé?

---

Pour comprendre cela, il faut faire la comparaison avec le langage C. Les variables sont déclarées tout en précisant le type avant toute opération alors que pour python, la reconnaissance du type correspondant se fait par python lui-même. 
De façon concrète, les choses se présentent comme suit : 

In [ ]:
#/* code C */. Stata est ecrit en C
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}

Le même code en python 

In [ ]:
# Le code en python
result = 0
for i in range(100):
    result += i

On peut rapidement faire la différence entre les deux codes. C exige que les types soit precisés alors Python n'en a pas besoin.  Il y a une flexibilité inconstestable en Python comme on peut le remarquer...mais cela a une contrepartie : le temps d'exécution qui semble plus long par rapport avec un code écrit en C. Cette faiblesse peut-elle encore être à l'ordre du jour avec des ordinateurs de plus en plus rapide. 
****
Nous n'irons pas dans les détails en ce qui concerne cette comparaison entre Python et C. Allons découvrir Python en pratique pour la Data Science. 


## Les bases des arrays 

**Apprenons créer des tableaux multidimensionnels avec Numpy**
***
Comment générer un tableau multidimensionnels de données avec Numpy? Pour les tableaux simples, on utilise les listes---structures de données---pour en créer.

In [1]:
# Importons le package/librarie/module numpy. As affecte un diminutif à numpy. On parle précisement d'alias
import numpy as np

In [16]:
# Generation des tableaux multidimensionnels
k=np.array([1,2,3,4,5])# Le plus simplement possible
m=np.array([[1,2,34],[2,3,4]]) # un tableau à partir d'une liste de liste
n=np.array(((1,2,3),(3,4,5))) # Au lieu des [], on peut utiliser (). Mais attention, il vaut mieux choisir []


**Les tableaux multidimensionnels et le type de données**
___
- Si l'ensemble des éléments de la liste peuvent être de type différent, comme une matrice, les élements du tableaux doivent de même type. Si possible, certaines données sont "contraintes". 
- L'exemple type c'est avec les données de type intègre qui sont convertis en type réel ou décimal dès qu'il y a un nombre réel ou décimal parmi les éléments du tableau. 

In [20]:
# Un exemple de upcasting fait par python
l=np.array([1,2.5,5,7]) # Tous les éléments de l sont devenus des décimaux. 


Le choix du type de données dans le tableau peut se faire dès la construction du tableau. Pour le faire on procède la façon suivante : 

In [26]:
p=np.array([1,2,3,4],dtype="float") # au lieu de int, on peut utiliser : int, float, int32,int64,float32,float64....

_Pour des tableaux de données réellement multidimensionnels_

Nous l'avons déjà fait plus haut(confère paragraphe concernant la génération des tableaux multidimensionnels), nous revenons pour mettre en exergue les sources de confusion auxquelles souvent nous sommes exposés. 

In [31]:
q=np.array([[1,2,3],[4,5,6]],dtype="float") # le nombre de liste constitue la dim1 du tableau.
# Le nombre d'éléments dans la liste constitue la dim2 du tableau
q

array([[1., 2., 3.],
       [4., 5., 6.]])

__Les routines natives de Python permettant de créer des tableaux multidimensionnels__
Pour créer des tableaux de données multidimensionnels,on peut si utile faire appel aux routines qui sont natives à python : 
- avec les zéros;
- avec les 1;
- avec la même valeur;
- des séquences de valeurs séparées par ...;
- ... valeurs comprises entre 0 et 1;
- un jeu de données distribuées uniformément entre 0 et 1 dans un tableau$(3x3)$
- un jeu de données distribuées normalement de loi N(0,1)
- un jeu de données de type intègre dans l'intervalle$[0,10)$
- une matrice identité $(3x3)$
- avec des valeurs(n'importe laquelle) présentent en mémoire




In [62]:
# Concretement
zero=np.zeros(10,dtype="int") 
zero_1=np.zeros((2,3),dtype="float")
one=np.ones(10)
one_1=np.ones((2,3),dtype="float64")
full=np.full(10,np.pi)
full_1=np.full((2,3),2)
arange=np.arange(0,20,2) 
linspace=np.linspace(0,1,5)
unif=np.random.random((3,3))
normal=np.random.normal(0,1,(3,3))
randint=np.random.randint(0,10,(3,3))
ident=np.eye(10)
empty=np.empty(10)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

**Les attributs des tableaux muldimensionnels de numpy**

_Les attributs_

Cette section porte sur les attributs des tableaux multidimensionnels : taille, dimension, type de données, consommation de la mémoire
_L'indexation : cas d'un seul élément_

Obtenir et modifier un élément du tableau

_Les sous-tableaux_

 Obtenir et modifier un sous-tableau dans un tableau de données plus grand
 
_Le redimensionnement des tableaux_

Modifier la dimension d'un tableau

_Concatener ou subdiviser un tableau_

Concatener plusieurs tableau en un seul et subdiviser un tableau en plusieurs.

___
Faisons les choses concrètement...
___

In [2]:
# Les attributs
np.random.seed(2213) #
x1=np.random.randint(0,10,7)
x1.ndim # nbre de dimension
x1.shape # Ordre du tableau multidimensionnel
x1.size # nbre d'éléments
x2=np.random.normal(1,3,(3,4))
x2.ndim
x2.shape
x2.size
x3=np.random.random((4,7,9))
x3.ndim
x3.shape
x3.size
## Autre attribut important...juste à titre indicatif
x3.dtype
taille=x3.itemsize # taille de l'objet x3 dans la memoire

# Indexation d'un seul élément
x4=np.random.randint(1,10,5) # array([9, 4, 2, 1, 2])
x4[0] # pour obtenir le premier élément
x4[4] # pour obtenir le dernier (5-1) élément
## utilisation des indices négatifs
x4[-1]
x4[-3]
x4[-5]
## raisonnons sur un tableau multidimensionnel
x5=np.random.random((2,3)) #array([[0.82195538, 0.42961994, 0.40522379],
                                 #[0.12419952, 0.5331591 , 0.02888004]])
x5[1,2]
#x5[2,2] signale erreur....compte tenu l'ordre du tableau et 0 comme debut de comptage
x5[0,-1] # -1 indique le dernier element...ici la derniere colonne

## On peut utiliser l'indexation pour modifier une valeur dans le tableau
x6=np.ones((3,2),dtype="int32")
x6[2,1]=5
x6[2,0]=0.5  # On remarque que 0.5 n'apparait pas mais 0. Python a voulu respecter le type de données du tableau initial


In [5]:
# Acceder à un sous-tableau
x7=np.random.normal(0,1,(7,3))
x7

array([[-0.31113857, -0.0609659 , -0.07393864],
       [-0.97474115, -2.20045831, -0.39187539],
       [-0.55575572, -0.25491652, -0.60723963],
       [ 1.72326101, -1.75655764,  0.2798671 ],
       [ 1.22173331, -0.81023074,  0.76830346],
       [ 0.36624572, -0.26095896,  1.77677379],
       [ 0.68903632,  0.28230958, -0.98561126]])

In [7]:
## Acceder au sous-tableau
x7_1=x7[2:]
x7_1

array([[-0.55575572, -0.25491652, -0.60723963],
       [ 1.72326101, -1.75655764,  0.2798671 ],
       [ 1.22173331, -0.81023074,  0.76830346],
       [ 0.36624572, -0.26095896,  1.77677379],
       [ 0.68903632,  0.28230958, -0.98561126]])

In [10]:
x7_2=x7[:2,1]
x7_2

array([-0.0609659 , -2.20045831])

## Sous-tableaux unidimensionnels de Numpy

In [8]:
x8=np.arange(10) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x8_1=x8[::2] ## retenir les nombres à partir de 0 en partant de 0
x8_2=x8[1::2] ## retenir les nombres à partir de 0 en partant de 1
x8_3=x8[::-1]
x8_4=x8[5::-2] # fait le meme travail mais en inversant avec le pas =-2

array([5, 3, 1])

## Acceder aux sous tableaux multidimensionnels de Numpy

In [13]:
x9=np.random.randint(0,10,(5,4))
x9_1=x9[:2,:3] # Extraction d'un tableau multidimensionnel 2 lignes, 3 colonnes
x9_2=x9[:3,::2] # Extraction d'un TD 3 lignes (0,1,2) et les colonnes selon un pas de 2 en benginning par 0
# On peut utiliser les valeurs negatives...
x9_3=x9[::-1,::-2]

array([[8, 9],
       [6, 8],
       [9, 4],
       [3, 6],
       [8, 4]])

## Acceder à des éléments d'un tableau multidimensionnel

In [23]:
x10=np.random.random((5,4))
x10_1=x10[2,3] # acceder a un element : position 2 et 3
x10_2=x10[:,1] # acceder la colonne 1
x10_3=x10[1,:] # acceder a la ligne 1  =x10[1]
x10_4=x10[1]

array([0.28440161, 0.34523114, 0.02794007, 0.73965024])

## Une vue ou une copie

Lorsque l'on extrait un sous tableau multidimensionnel de données, contrairement à d'autres langages où le sous-tableau est indépendant, cela n'est pas le cas chez Pyhton. C'est une vue qui est extraite ou créer. 

La conséquence remarquable est que cette vue (une sorte de copie )reste liée à au tableau dont elle est issue. On peut le voir en concrètement : 

In [12]:
m= np.random.normal(0,1,(4,5))
m_1=m[:3,::2]
#array([[ 1.5452263 , -0.28246864, -1.30583321,  0.55801015, -0.01412886],
#       [ 1.5634321 , -0.8729321 , -0.46186281,  0.77891609,  0.4067519 ],
#       [ 0.34912937, -1.15370473,  0.30293115,  0.47600557, -0.68059335],
#       [-0.93793751,  0.04919251,  1.25983511, -0.81346766,  0.42117295]])
# 
#m_1 array([[-2.28126538, -1.35363821, -0.28234879],
#       [ 3.60013259,  1.68797721,  1.0855391 ],
#       [-0.73551981,  1.66611382,  1.59034498]])
# Nous allons modifier une valeur dans m_1, 
m_1[0,0]=1
#array([[ 1.        , -0.55947367, -0.77731252],
#       [-1.01232315, -0.84191502, -0.93326354],
#       [-0.07387897, -0.43551456, -0.41799563]])
m 

array([[ 1.        ,  0.21455022,  1.16383876,  0.52418796,  1.83323499],
       [ 1.14597158,  0.84470227, -0.21460153, -0.53504956,  0.62260077],
       [-0.90960016, -1.26021147, -0.08790876,  1.24567512, -0.19937141],
       [-0.24447109,  0.78693425, -0.1214313 , -0.21844466, -1.61076564]])

On peut faire le constat que la valeur à la position (0,0) dans le tableau de données multidimensionnel de départ a bien été modifié.

Cela a sans doute des avantages dans la manipulation des données de grand volume ; mais ne peut manquer de poser des problèmes par moment lorsque nous ne voulons pas modifier les données de base en mémoire. On utilise la fonction copy() dans Python à cet effet. 

Utilisons cette fonction ....

In [14]:
m_1_copy=m_1.copy()
m_1_copy[0,0]=42
m_1_copy

array([[42.        ,  1.16383876,  1.83323499],
       [ 1.14597158, -0.21460153,  0.62260077],
       [-0.90960016, -0.08790876, -0.19937141]])

## Les principales opérations possibles avec les arrays dans numpy

array([-0.0609659 , -2.20045831])

## Les aggrégations : min, max 

## Les opérations sur les arrays : broadcasting

## Les comparaisons, mask et logique booléenne

## L'indexation

## Trier dans l'array

## Données structurées dans Numpy

# Manipulation des données avec Pandas

# Visualisation avec Matplotlib

# Apprentissage machine